
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User112
 */
public class frame8 extends javax.swing.JFrame {

    /**
     * Creates new form frame8
     */
    Connection con;

    public frame8() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "root");
            Statement st = con.createStatement();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Profit/Resource Availability Maximization  on Confederated Cloud Environment");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 570, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Jobs to be allocated");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 30));

        jButton2.setText("Available resources");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 130, 30));

        jButton3.setText("Allocate Jobs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 110, 30));

        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 580, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 580, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<Integer> jobsize=new ArrayList<Integer>();
             jTextArea1.setText("");
            jTextArea1.append("\t\tJobs To be Allocated\n\n");
            jTextArea1.append("Job Id\tBroker Id\tLength\tfile size\tOutput Size\tPriority\tValue\n");
            jTextArea1.append("======================================================================\n");
            Statement str=con.createStatement();
            ResultSet rs=str.executeQuery("select * from cloudlet ");
            while(rs.next())
            {
             
                int opsize=rs.getInt(5);
                jobsize.add(opsize);
//                String pri=rs.getString(6);
//                int val=rs.getInt(7);
            
            }
            System.out.println(jobsize);
            Collections.sort(jobsize);
            System.out.println(jobsize);
            int min=jobsize.get(0);
            int max=jobsize.get(jobsize.size()-1);
            System.out.println(min+","+max);
            int div1=(max/3);
            System.out.println(div1+"\t"+(div1*2)+"\t"+(div1*3));
           
            Statement st=con.createStatement();
            ResultSet rse=st.executeQuery("select * from cloudlet ");
            while(rse.next())
            {
                 int jid=rse.getInt(1);
                int brid=rse.getInt(2);
                int length=rse.getInt(3);
                int fsize=rse.getInt(4);
                int opsize=rse.getInt(5);
                if(opsize<div1){
                    String p="low"; int val=3;
                Statement stu=con.createStatement();
                stu.executeUpdate("update cloudlet set priority='low', value='"+3+"' where id='"+jid+"'");
                jTextArea1.append(jid+"\t"+brid+"\t"+length+"\t"+fsize+"\t"+opsize+"\t"+p+"\t"+val+"\n\n");    
                }
                if((opsize>div1 || opsize==div1)&&(opsize<(div1*2))){
                    String p="medium"; int val=2;
                Statement stu=con.createStatement();
                stu.executeUpdate("update cloudlet set priority='medium', value='"+2+"' where id='"+jid+"'");
                jTextArea1.append(jid+"\t"+brid+"\t"+length+"\t"+fsize+"\t"+opsize+"\t"+p+"\t"+val+"\n\n");    
                }
                if((opsize>(div1*2)) || opsize==(div1*2)){
                    String p="high"; int val=1;
                Statement stu=con.createStatement();
                stu.executeUpdate("update cloudlet set priority='high', value='"+1+"' where id='"+jid+"'");
                jTextArea1.append(jid+"\t"+brid+"\t"+length+"\t"+fsize+"\t"+opsize+"\t"+p+"\t"+val+"\n\n");    
                }
            }
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            jTextArea1.setText("");
            jTextArea1.append("\t\tavailable Resources\n\n");
            jTextArea1.append("Vm Id\t Broker Id\t Mips\t Ram \t Bandwidth\t Placed In\t Capacity\n");
            jTextArea1.append("======================================================================================\n");
            Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select * from vtable");
         while(rs.next())
         {
             jTextArea1.append(rs.getInt(1)+"\t"+rs.getInt(2)+"\t"+rs.getInt(3)+"\t"+rs.getInt(4)+"\t"+rs.getInt(5)+"\t"+rs.getString(6)+"\t"+rs.getInt(8)+"\n");
         }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            jTextArea1.setText("");
                int jid;
                int brid;
                int fs;
                String prty;
     
            Statement st=con.createStatement();
            ResultSet rsy=st.executeQuery("select * from cloudlet order by value Asc");
            while(rsy.next())
            {
                int flag=0;
                   jid=rsy.getInt(1);
                   brid=rsy.getInt(2);
                   fs=rsy.getInt(4);
                   
                   prty=rsy.getString(6);
                   System.out.println(jid+"\t"+brid+"\t"+fs+"\t"+prty);
                   jTextArea1.append("Job ID: "+jid+" Allocated Broker "+brid+" JobSize is "+fs+" With Priority "+prty+"\n");
                   int id; int capbw; String pl; String stat;
                       Statement st2=con.createStatement();
                        ResultSet rst=st2.executeQuery("select * from vtable where brokerid='"+brid+"'");
                        while(rst.next())
                        {
                            id=rst.getInt(1);
                             pl=rst.getString(6);
                            stat=rst.getString(7);
                            capbw=rst.getInt(8);
                            System.out.println("checking vm"+id+"with  cap"+capbw+"placed in"+pl+" status is "+stat);
                            jTextArea1.append("checking vm"+id+" with  cap "+capbw+" placed in "+pl+" status is "+stat+"\n");
                            if((fs<=capbw) && stat.equalsIgnoreCase("ready"))
                            {
                                System.out.println("Printing & checking");
                                //jTextArea1.append("Printing & checking"+"\n");
                                capbw=capbw-fs;
                                System.out.println(jid+" can be alloted to vm"+id+ " through broker"+brid);
                                jTextArea1.append(jid+"can be alloted to vm"+id+ "through broker"+brid+"\n");
                                System.out.println("remaining capacity is"+capbw);
                                jTextArea1.append("remaining capacity in vm"+id+" is "+capbw+"\n");
                                Statement ste=con.createStatement();
                                ste.executeUpdate("update vtable set capacity='"+capbw+"' where vmid='"+id+"'");
                                String v="vm"+id;
                                Statement str=con.createStatement();
                                str.executeUpdate("update cloudlet set allotedvm='"+v+"' where id='"+jid+"'");
                                flag=1;
                                jTextArea1.append("\n\n");
                            }
                            
                            else{
                                String v="vm not alloted";
                                Statement str=con.createStatement();
                                str.executeUpdate("update cloudlet set allotedvm='"+v+"' where id='"+jid+"'");
                                System.out.println(jid+"is not Allocated to a vm");
                            }
                            if(flag==1)
                            break;
                        }
                        if (flag==0)
                        {
                              String v="vm not alloted";
                                Statement str=con.createStatement();
                                str.executeUpdate("update cloudlet set allotedvm='"+v+"' where id='"+jid+"'");
                            jTextArea1.append(jid+ "is not Placed, VMs not Available with required Resources\n\n");
                        }
                   
                   
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        frame9 f9=new frame9();
        f9.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame8().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
